import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className="bg-gray-700 text-white">
          <h2>MEUS PRODUTOS</h2>
          <ul>
          <li>
              <Link href="/">HOME</Link>
            </li>
            <li>
              <Link href="/produtos/calca">CALÇA</Link>
            </li>
            <li>
              <Link href="/produtos/camisa">CAMISA</Link>
            </li>
            <li>
              <Link href="/produtos/meia">MEIA</Link>
            </li>
            <li>
              <Link href="/produtos/tenis">TÊNIS</Link>
            </li>
          </ul>
        </header>

        {children}
      </body>
    </html>
  );
}
